import { db } from "./db";
import { agentRegistry } from "@shared/schema";
import type { InsertAgentRegistryEntry } from "@shared/schema";

const agentSeedData: InsertAgentRegistryEntry[] = [
  // Lead Intake Stage
  {
    agentKey: "lead_intake_agent",
    displayName: "Lead Intake Agent",
    purpose: "Capture and qualify incoming leads from all channels",
    description: "Parses inbound messages, missed calls, and web forms to extract customer intent, contact info, and service requests. Routes qualified leads to the quoting stage.",
    category: "ops",
    stage: "lead_intake",
    domains: ["messaging"],
    triggers: ["missed_call", "inbound_sms", "web_lead"],
    status: "active",
    inputSchema: { type: "object", properties: { source: { type: "string" }, phone: { type: "string" }, message: { type: "string" } } },
    outputSchema: { type: "object", properties: { leadId: { type: "number" }, qualified: { type: "boolean" }, intent: { type: "string" } } },
  },
  
  // Quoting Stage
  {
    agentKey: "quote_builder_agent",
    displayName: "Quote Builder Agent",
    purpose: "Calculate and generate accurate service quotes",
    description: "Uses lot size data, service type, and pricing policies to generate price range estimates. Incorporates complexity factors and seasonal adjustments.",
    category: "ops",
    stage: "quoting",
    domains: ["pricing"],
    triggers: ["lead_qualified", "quote_requested"],
    status: "active",
    inputSchema: { type: "object", properties: { lotSqft: { type: "number" }, serviceType: { type: "string" }, frequency: { type: "string" } } },
    outputSchema: { type: "object", properties: { minPrice: { type: "number" }, maxPrice: { type: "number" }, confidence: { type: "string" } } },
  },
  {
    agentKey: "lot_size_resolver",
    displayName: "Lot Size Resolver",
    purpose: "Determine property lot size from address",
    description: "Uses FREE-FIRST resolution strategy with multi-tier caching (geocode, parcel) and ArcGIS integration to provide accurate property data.",
    category: "ops",
    stage: "quoting",
    domains: ["integrations"],
    triggers: ["address_provided"],
    status: "active",
    inputSchema: { type: "object", properties: { address: { type: "string" }, zip: { type: "string" } } },
    outputSchema: { type: "object", properties: { lotSqft: { type: "number" }, source: { type: "string" }, confidence: { type: "string" } } },
  },
  
  // Confirmation Stage
  {
    agentKey: "quote_confirm_agent",
    displayName: "Quote Confirmation Agent",
    purpose: "Parse customer responses to quotes",
    description: "Interprets customer replies to determine acceptance, rejection, modification requests, or questions. Routes to appropriate next stage.",
    category: "ops",
    stage: "confirmation",
    domains: ["messaging"],
    triggers: ["customer_reply"],
    status: "active",
    inputSchema: { type: "object", properties: { quoteId: { type: "number" }, response: { type: "string" } } },
    outputSchema: { type: "object", properties: { action: { type: "string" }, reason: { type: "string" } } },
  },
  
  // Scheduling Stage
  {
    agentKey: "schedule_propose_agent",
    displayName: "Schedule Proposal Agent",
    purpose: "Generate optimal time windows for service",
    description: "Analyzes crew availability, travel distances, and customer preferences to propose available scheduling windows.",
    category: "ops",
    stage: "scheduling",
    domains: ["routing"],
    triggers: ["quote_accepted"],
    status: "active",
    inputSchema: { type: "object", properties: { jobRequestId: { type: "number" }, preferredDays: { type: "array" } } },
    outputSchema: { type: "object", properties: { windows: { type: "array" }, recommended: { type: "object" } } },
  },
  
  // Crew Assignment Stage
  {
    agentKey: "crew_simulation_agent",
    displayName: "Crew Simulation Agent",
    purpose: "Simulate crew assignments for optimal matching",
    description: "Runs simulations to evaluate eligible crews based on skills, equipment, travel time, and margin impact. Produces ranked recommendations.",
    category: "ops",
    stage: "crew_assignment",
    domains: ["routing", "pricing"],
    triggers: ["time_selected"],
    status: "active",
    inputSchema: { type: "object", properties: { jobRequestId: { type: "number" }, targetDate: { type: "string" } } },
    outputSchema: { type: "object", properties: { simulations: { type: "array" }, topPick: { type: "object" } } },
  },
  {
    agentKey: "feasibility_check_agent",
    displayName: "Feasibility Check Agent",
    purpose: "Validate job feasibility before booking",
    description: "Checks crew capacity, equipment availability, travel constraints, and scheduling conflicts to ensure jobs can be completed as planned.",
    category: "ops",
    stage: "crew_assignment",
    domains: ["routing"],
    triggers: ["simulation_complete"],
    status: "active",
    inputSchema: { type: "object", properties: { simulationId: { type: "number" } } },
    outputSchema: { type: "object", properties: { feasible: { type: "boolean" }, issues: { type: "array" } } },
  },
  {
    agentKey: "margin_validate_agent",
    displayName: "Margin Validation Agent",
    purpose: "Ensure jobs meet profitability thresholds",
    description: "Calculates margin score based on travel costs, labor, and revenue. Jobs below 70% threshold require manual approval.",
    category: "finance",
    stage: "crew_assignment",
    domains: ["pricing"],
    triggers: ["feasibility_passed"],
    status: "active",
    inputSchema: { type: "object", properties: { simulationId: { type: "number" }, price: { type: "number" } } },
    outputSchema: { type: "object", properties: { marginScore: { type: "number" }, approved: { type: "boolean" } } },
  },
  
  // Booking Stage
  {
    agentKey: "crew_lock_agent",
    displayName: "Crew Lock Agent",
    purpose: "Finalize crew assignment and create schedule",
    description: "Locks in crew assignment for approved jobs. High confidence assignments (score ≥80, margin ≥70) auto-approve; others queue for ops review.",
    category: "ops",
    stage: "booking",
    domains: ["routing"],
    triggers: ["margin_validated"],
    status: "active",
    inputSchema: { type: "object", properties: { decisionId: { type: "number" } } },
    outputSchema: { type: "object", properties: { scheduleItemId: { type: "number" }, status: { type: "string" } } },
  },
  {
    agentKey: "dispatch_agent",
    displayName: "Dispatch Agent",
    purpose: "Create dispatch tasks and route sequences",
    description: "Generates optimized route sequences for crews. Uses greedy algorithm with Haversine distance for efficient daily routes.",
    category: "ops",
    stage: "booking",
    domains: ["routing", "fsm"],
    triggers: ["crew_locked"],
    status: "active",
    inputSchema: { type: "object", properties: { crewId: { type: "number" }, date: { type: "string" } } },
    outputSchema: { type: "object", properties: { routeSequence: { type: "array" }, totalDistance: { type: "number" } } },
  },
  
  // Retention & Insights Stage
  {
    agentKey: "customer_memory_agent",
    displayName: "Customer Memory Agent",
    purpose: "Build and recall customer context",
    description: "Stores and retrieves customer interactions, preferences, and history using vector embeddings for semantic search. Enriches future interactions.",
    category: "core",
    stage: "retention_insights",
    domains: ["memory"],
    triggers: ["interaction_complete", "context_needed"],
    status: "active",
    inputSchema: { type: "object", properties: { customerId: { type: "number" }, query: { type: "string" } } },
    outputSchema: { type: "object", properties: { memories: { type: "array" }, insights: { type: "object" } } },
  },
  {
    agentKey: "renewal_upsell_agent",
    displayName: "Renewal & Upsell Agent",
    purpose: "Generate renewal offers and upsell opportunities",
    description: "Weekly scan for clients with completed jobs. Computes next-best-offer by service, season, and lot size. Creates draft quotes for qualified leads.",
    category: "finance",
    stage: "retention_insights",
    domains: ["pricing", "messaging"],
    triggers: ["weekly_scan", "job_completed"],
    status: "active",
    inputSchema: { type: "object", properties: { customerId: { type: "number" }, lastService: { type: "string" } } },
    outputSchema: { type: "object", properties: { offers: { type: "array" }, recommended: { type: "object" } } },
  },
  
  // Integrations Stage
  {
    agentKey: "jobber_sync_agent",
    displayName: "Jobber Sync Agent",
    purpose: "Sync data with Jobber FSM",
    description: "Handles bidirectional sync with Jobber. Processes webhooks, enriches data via GraphQL, manages OAuth tokens, and writes job/client updates.",
    category: "integrations",
    stage: "integrations",
    domains: ["integrations", "fsm"],
    triggers: ["jobber_webhook", "sync_requested"],
    status: "needs_config",
    inputSchema: { type: "object", properties: { eventType: { type: "string" }, payload: { type: "object" } } },
    outputSchema: { type: "object", properties: { synced: { type: "boolean" }, jobberIds: { type: "object" } } },
  },
  {
    agentKey: "customer_comms_agent",
    displayName: "Customer Comms Agent",
    purpose: "Send customer-facing messages",
    description: "Produces compliant customer messages with strict tone rules. Uses templates by service category. Writes Jobber comm log pointers.",
    category: "comms",
    stage: "integrations",
    domains: ["messaging", "fsm"],
    triggers: ["schedule_update", "job_completed", "send_notification"],
    status: "active",
    inputSchema: { type: "object", properties: { templateKey: { type: "string" }, customerId: { type: "number" }, data: { type: "object" } } },
    outputSchema: { type: "object", properties: { messageSent: { type: "boolean" }, twilioSid: { type: "string" } } },
  },
  {
    agentKey: "reconciliation_agent",
    displayName: "Reconciliation Agent",
    purpose: "Validate invoice/payment integrity",
    description: "Compares paid_total against sum of payments. Creates alerts for mismatches >$0.01. Updates Jobber RECON_STATUS custom field.",
    category: "finance",
    stage: "integrations",
    domains: ["integrations", "fsm"],
    triggers: ["payment_received", "daily_scan"],
    status: "active",
    inputSchema: { type: "object", properties: { invoiceId: { type: "string" } } },
    outputSchema: { type: "object", properties: { status: { type: "string" }, variance: { type: "number" } } },
  },
  
  // Core (Hidden) - Orchestrators
  {
    agentKey: "lead_to_cash_orchestrator",
    displayName: "Lead-to-Cash Orchestrator",
    purpose: "Manage the full 10-stage lead lifecycle",
    description: "Central orchestrator that coordinates all agents through the deterministic workflow. Handles stage transitions, human-in-loop approvals, and seamless resumption.",
    category: "core",
    stage: "core",
    domains: ["orchestration"],
    triggers: ["new_lead", "stage_complete", "approval_received"],
    status: "active",
    inputSchema: { type: "object", properties: { leadId: { type: "number" }, currentStage: { type: "string" } } },
    outputSchema: { type: "object", properties: { nextStage: { type: "string" }, actionsTriggered: { type: "array" } } },
  },
  {
    agentKey: "optimizer_orchestrator",
    displayName: "Optimizer Orchestrator",
    purpose: "Manage crew assignment decision workflow",
    description: "Coordinates simulation, feasibility, margin validation, and crew lock stages. Enforces RBAC for approvals. Tracks decision lifecycle from draft to written_back.",
    category: "core",
    stage: "core",
    domains: ["orchestration", "routing"],
    triggers: ["job_request_created", "decision_needed"],
    status: "active",
    inputSchema: { type: "object", properties: { jobRequestId: { type: "number" } } },
    outputSchema: { type: "object", properties: { decisionId: { type: "number" }, status: { type: "string" } } },
  },
  {
    agentKey: "supervisor_agent",
    displayName: "Supervisor Agent",
    purpose: "Oversee all agent activities and handle exceptions",
    description: "Monitors agent health, handles failures, manages retries via DLQ, and escalates unresolvable issues to human operators.",
    category: "core",
    stage: "core",
    domains: ["orchestration"],
    triggers: ["agent_error", "health_check"],
    status: "active",
    inputSchema: { type: "object", properties: { agentId: { type: "number" }, eventType: { type: "string" } } },
    outputSchema: { type: "object", properties: { action: { type: "string" }, escalated: { type: "boolean" } } },
  },
  {
    agentKey: "dlq_processor",
    displayName: "Dead Letter Queue Processor",
    purpose: "Retry failed webhook processing",
    description: "Manages failed webhooks with exponential backoff retry strategy. Tracks attempts and escalates persistent failures.",
    category: "core",
    stage: "core",
    domains: ["orchestration", "integrations"],
    triggers: ["dlq_item_added", "retry_scheduled"],
    status: "active",
    inputSchema: { type: "object", properties: { itemId: { type: "number" } } },
    outputSchema: { type: "object", properties: { retried: { type: "boolean" }, nextRetryAt: { type: "string" } } },
  },
  
  // General-Purpose AI Agents (lawnflow-agents)
  {
    agentKey: "inbound_intake",
    displayName: "Inbound Intake Agent",
    purpose: "AI-powered lead intake and enrichment",
    description: "Uses AI to interpret customer messages, extract intent, and enrich lead data. Handles complex conversations and qualification.",
    category: "ops",
    stage: "lead_intake",
    domains: ["messaging", "ai"],
    triggers: ["inbound_sms", "web_chat", "phone_transcript"],
    status: "active",
    inputSchema: { type: "object", properties: { message: { type: "string" }, channel: { type: "string" } } },
    outputSchema: { type: "object", properties: { intent: { type: "string" }, entities: { type: "object" }, nextAction: { type: "string" } } },
  },
  {
    agentKey: "pricing_profit",
    displayName: "Pricing & Profit Optimization Agent",
    purpose: "AI-powered pricing optimization",
    description: "Analyzes market conditions, customer history, and profitability to recommend optimal pricing strategies.",
    category: "finance",
    stage: "quoting",
    domains: ["pricing", "ai"],
    triggers: ["quote_requested", "price_optimization"],
    status: "active",
    inputSchema: { type: "object", properties: { services: { type: "array" }, lotSize: { type: "number" }, history: { type: "object" } } },
    outputSchema: { type: "object", properties: { recommendedPrice: { type: "number" }, reasoning: { type: "array" }, confidence: { type: "string" } } },
  },
  {
    agentKey: "scheduling_dispatch",
    displayName: "Scheduling & Dispatch Agent",
    purpose: "AI-powered scheduling optimization",
    description: "Optimizes crew schedules considering availability, skills, travel time, and customer preferences.",
    category: "ops",
    stage: "scheduling",
    domains: ["routing", "ai"],
    triggers: ["schedule_request", "dispatch_optimization"],
    status: "active",
    inputSchema: { type: "object", properties: { jobId: { type: "number" }, preferredDate: { type: "string" }, crewOptions: { type: "array" } } },
    outputSchema: { type: "object", properties: { scheduledDate: { type: "string" }, crewId: { type: "number" }, reasoning: { type: "array" } } },
  },
  {
    agentKey: "job_creation",
    displayName: "Job Creation Agent",
    purpose: "Automate job creation in FSM",
    description: "Creates jobs in Field Service Management system with all required data and attachments.",
    category: "ops",
    stage: "booking",
    domains: ["fsm", "integrations"],
    triggers: ["job_approved", "create_job"],
    status: "active",
    inputSchema: { type: "object", properties: { jobRequestId: { type: "number" }, crewId: { type: "number" }, schedule: { type: "object" } } },
    outputSchema: { type: "object", properties: { jobId: { type: "string" }, fsmJobId: { type: "string" }, status: { type: "string" } } },
  },
  {
    agentKey: "crew_notification",
    displayName: "Crew Notification Agent",
    purpose: "Send notifications to crew members",
    description: "Sends job assignments, updates, and alerts to crew members via SMS and push notifications.",
    category: "comms",
    stage: "booking",
    domains: ["messaging"],
    triggers: ["job_assigned", "schedule_changed", "urgent_alert"],
    status: "active",
    inputSchema: { type: "object", properties: { crewId: { type: "number" }, message: { type: "string" }, priority: { type: "string" } } },
    outputSchema: { type: "object", properties: { sent: { type: "boolean" }, recipients: { type: "array" }, timestamp: { type: "string" } } },
  },
  {
    agentKey: "job_monitoring",
    displayName: "Job Monitoring Agent",
    purpose: "Monitor job progress and detect issues",
    description: "Tracks job status in real-time, detects delays or problems, and escalates when needed.",
    category: "ops",
    stage: "execution",
    domains: ["monitoring"],
    triggers: ["job_started", "status_update", "check_in"],
    status: "active",
    inputSchema: { type: "object", properties: { jobId: { type: "number" }, status: { type: "string" } } },
    outputSchema: { type: "object", properties: { onTrack: { type: "boolean" }, issues: { type: "array" }, actions: { type: "array" } } },
  },
  {
    agentKey: "quality_assurance",
    displayName: "Quality Assurance Agent",
    purpose: "Automated quality checks",
    description: "Analyzes job completion data, photos, and customer feedback to assess quality and identify issues.",
    category: "ops",
    stage: "completion",
    domains: ["ai", "monitoring"],
    triggers: ["job_completed", "photos_uploaded", "qa_check"],
    status: "active",
    inputSchema: { type: "object", properties: { jobId: { type: "number" }, photos: { type: "array" }, notes: { type: "string" } } },
    outputSchema: { type: "object", properties: { qualityScore: { type: "number" }, issues: { type: "array" }, approved: { type: "boolean" } } },
  },
  {
    agentKey: "completion_finalization",
    displayName: "Completion Finalization Agent",
    purpose: "Finalize job completion",
    description: "Handles all post-job tasks: invoicing, customer notification, review requests, and follow-up scheduling.",
    category: "ops",
    stage: "completion",
    domains: ["fsm", "messaging"],
    triggers: ["job_completed", "qa_passed"],
    status: "active",
    inputSchema: { type: "object", properties: { jobId: { type: "number" }, qualityReport: { type: "object" } } },
    outputSchema: { type: "object", properties: { invoiced: { type: "boolean" }, customerNotified: { type: "boolean" }, followUpScheduled: { type: "boolean" } } },
  },
  {
    agentKey: "customer_notification",
    displayName: "Customer Notification Agent",
    purpose: "Send notifications to customers",
    description: "Sends appointment reminders, job updates, completion notices, and review requests to customers.",
    category: "comms",
    stage: "retention_insights",
    domains: ["messaging"],
    triggers: ["schedule_confirmed", "job_started", "job_completed", "review_request"],
    status: "active",
    inputSchema: { type: "object", properties: { customerId: { type: "number" }, messageType: { type: "string" }, data: { type: "object" } } },
    outputSchema: { type: "object", properties: { sent: { type: "boolean" }, channel: { type: "string" }, timestamp: { type: "string" } } },
  },
  {
    agentKey: "crew_support",
    displayName: "Crew Support Agent",
    purpose: "AI assistant for crew questions",
    description: "Provides crews with instant answers to questions about procedures, equipment, and customer info.",
    category: "ops",
    stage: "execution",
    domains: ["ai", "knowledge"],
    triggers: ["crew_question", "help_request"],
    status: "active",
    inputSchema: { type: "object", properties: { question: { type: "string" }, context: { type: "object" } } },
    outputSchema: { type: "object", properties: { answer: { type: "string" }, sources: { type: "array" }, confidence: { type: "string" } } },
  },
  {
    agentKey: "follow_up_scheduler",
    displayName: "Follow-Up Scheduler Agent",
    purpose: "Schedule follow-up activities",
    description: "Automatically schedules follow-up calls, emails, and service reminders based on customer lifecycle.",
    category: "ops",
    stage: "retention_insights",
    domains: ["automation"],
    triggers: ["job_completed", "customer_milestone"],
    status: "active",
    inputSchema: { type: "object", properties: { customerId: { type: "number" }, trigger: { type: "string" } } },
    outputSchema: { type: "object", properties: { scheduled: { type: "boolean" }, date: { type: "string" }, type: { type: "string" } } },
  },
  {
    agentKey: "customer_follow_up",
    displayName: "Customer Follow-Up Agent",
    purpose: "Execute customer follow-ups",
    description: "Handles scheduled follow-ups with customers, gathering feedback and identifying opportunities.",
    category: "comms",
    stage: "retention_insights",
    domains: ["messaging", "ai"],
    triggers: ["follow_up_due", "satisfaction_check"],
    status: "active",
    inputSchema: { type: "object", properties: { customerId: { type: "number" }, followUpType: { type: "string" } } },
    outputSchema: { type: "object", properties: { completed: { type: "boolean" }, feedback: { type: "object" }, nextSteps: { type: "array" } } },
  },
  {
    agentKey: "customer_service",
    displayName: "Customer Service Agent",
    purpose: "AI-powered customer support",
    description: "Handles customer inquiries, complaints, and requests using AI with knowledge base and escalation.",
    category: "comms",
    stage: "retention_insights",
    domains: ["ai", "messaging"],
    triggers: ["customer_inquiry", "complaint", "support_request"],
    status: "active",
    inputSchema: { type: "object", properties: { customerId: { type: "number" }, message: { type: "string" }, channel: { type: "string" } } },
    outputSchema: { type: "object", properties: { response: { type: "string" }, resolved: { type: "boolean" }, escalate: { type: "boolean" } } },
  },
  {
    agentKey: "manager_escalation",
    displayName: "Manager Escalation Agent",
    purpose: "Escalate issues to managers",
    description: "Identifies situations requiring manager attention and creates escalation tickets with context.",
    category: "ops",
    stage: "core",
    domains: ["escalation"],
    triggers: ["high_priority_issue", "customer_complaint", "quality_failure"],
    status: "active",
    inputSchema: { type: "object", properties: { issueType: { type: "string" }, context: { type: "object" }, priority: { type: "string" } } },
    outputSchema: { type: "object", properties: { escalated: { type: "boolean" }, ticketId: { type: "string" }, assignedTo: { type: "string" } } },
  },
  {
    agentKey: "escalation_monitor",
    displayName: "Escalation Monitor Agent",
    purpose: "Track escalation resolution",
    description: "Monitors open escalations, sends reminders, and ensures timely resolution of critical issues.",
    category: "ops",
    stage: "core",
    domains: ["monitoring", "escalation"],
    triggers: ["escalation_created", "sla_check", "daily_review"],
    status: "active",
    inputSchema: { type: "object", properties: { ticketId: { type: "string" } } },
    outputSchema: { type: "object", properties: { status: { type: "string" }, overdue: { type: "boolean" }, actions: { type: "array" } } },
  },
];

export async function seedAgents() {
  console.log("Seeding agents...");
  
  const { eq } = await import("drizzle-orm");
  
  for (const agent of agentSeedData) {
    const [existingAgent] = await db
      .select()
      .from(agentRegistry)
      .where(eq(agentRegistry.agentKey, agent.agentKey))
      .limit(1);
    
    if (!existingAgent) {
      await db.insert(agentRegistry).values(agent);
      console.log(`  Created agent: ${agent.displayName}`);
    } else {
      console.log(`  Agent exists: ${agent.displayName}`);
    }
  }
  
  console.log("Agent seeding complete!");
}
